name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Change directory to backend
      run: pushd backend
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet msbuild --configuration Release --no-restore
    - name: Change directory to root
      run: popd
    - name: Change directory to backend tests
      run: pushd backend\test\ILSpy.Host.Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
