name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: submodule init
      run: git submodule init
    - name: submodule update
      run: git submodule update
    - name: Install dependencies
      run: dotnet restore backend/ILSpy-server.sln
    - name: Build
      run: dotnet msbuild backend/ILSpy-server.sln
    - name: Test
      run: dotnet test backend\test\ILSpy.Host.Tests\ILSpy.Host.Tests.csproj --no-restore --verbosity normal
