name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: submodule init
      run: git submodule init
    - name: submodule update
      run: git submodule update
    - name: Install backend dependencies
      run: dotnet restore backend/ILSpy-server.sln
    - name: Build backend
      run: dotnet msbuild backend/ILSpy-server.sln
    - name: Test backend
      run: dotnet test backend\test\ILSpy.Host.Tests\ILSpy.Host.Tests.csproj --no-restore --verbosity normal
      continue-on-error: true
    - name: Publish backend ILSpy.Host
      run: dotnet publish backend/src/ILSpy.Host/ILSpy.Host.csproj -f net472 -c release -r win7-x64 -o  vscode-extension\bin\ilspy-host
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install extension dependencies
      run: cd vscode-extension && npm install
    - name: Compile extension
      run: cd vscode-extension && npm run compile
    - name: Test extension
      run: cd vscode-extension && npm test
    - name: Install vsce
      run: npm i vsce -g
    - name: Pack extension
      run: cd vscode-extension && vsce package -o ilspy-vscode-%GITHUB_RUN_NUMBER%.vsix 
    - uses: actions/upload-artifact@v1
      with:
        name: extension-vsix
        path: vscode-extension/ilspy-vscode-%GITHUB_RUN_NUMBER%.vsix
    - name: Resotre directory
      run: popd
      shell: cmd
